# Generated by Django 4.2.27 on 2025-12-29 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveuniverse', '0011_extend_industry_activites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corptools', '0127_alter_corporationaudit_options'),
        ('fittings', '0016_remove_dogmaattribute_type_remove_dogmaeffect_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access this app'), ('review_subsidy', 'Can Review/Approve/Deny Subsidies'), ('subsidy_admin', 'Can adjust subsidy settings')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SubsidyConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_basis', models.CharField(choices=[('sell', 'Jita Sell'), ('buy', 'Jita Buy')], default='sell', max_length=4)),
                ('pct_over_basis', models.DecimalField(decimal_places=4, default=0.1, help_text='e.g. 0.10 for 10%', max_digits=6)),
                ('cost_per_m3', models.DecimalField(decimal_places=4, default=250, max_digits=20)),
                ('rounding_increment', models.IntegerField(default=250000, help_text='ISK rounding increment')),
                ('deleted_check', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subsidy Configuration',
                'verbose_name_plural': 'Subsidy Configuration',
            },
        ),
        migrations.CreateModel(
            name='SubsidyItemPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('buy', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eve_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_price', to='eveuniverse.evetype')),
            ],
            options={
                'verbose_name': 'Subsidy Item Price',
                'verbose_name_plural': 'Subsidy Item Prices',
            },
        ),
        migrations.CreateModel(
            name='UserTablePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_key', models.CharField(db_index=True, default='contracts', max_length=100)),
                ('sort_idx', models.IntegerField(default=0)),
                ('sort_dir', models.CharField(default='desc', max_length=4)),
                ('filters_json', models.TextField(blank=True, default='{}')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aasubsidy_table_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Table Preference',
                'verbose_name_plural': 'User Table Preferences',
                'unique_together': {('user', 'table_key')},
            },
        ),
        migrations.CreateModel(
            name='FittingClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_claims', to='fittings.fitting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_fitting_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fitting Claim',
                'verbose_name_plural': 'Fitting Claims',
                'unique_together': {('fitting', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CorporateContractSubsidy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.SmallIntegerField(default=0, help_text='1=Approved, -1=Rejected, 0=Pending')),
                ('subsidy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('paid', models.BooleanField(default=False)),
                ('exempt', models.BooleanField(default=False)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aasubsidy_meta', to='corptools.corporatecontract')),
                ('forced_fitting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forced_contracts', to='fittings.fitting')),
            ],
            options={
                'verbose_name': 'Corporate Contract Subsidy',
                'verbose_name_plural': 'Corporate Contract Subsidies',
                'indexes': [models.Index(fields=['contract'], name='uniqs_subsidy_per_contract'), models.Index(fields=['review_status'], name='ccs_review_status_idxs'), models.Index(fields=['paid'], name='ccs_paid_idxs'), models.Index(fields=['exempt'], name='ccs_exempt_idxs'), models.Index(fields=['subsidy_amount'], name='ccs_subsidy_amount_idxs'), models.Index(fields=['reason'], name='ccs_reason_idxs')],
            },
        ),
        migrations.AddConstraint(
            model_name='corporatecontractsubsidy',
            constraint=models.UniqueConstraint(fields=('contract',), name='uniq_subsidy_per_contract'),
        ),
    ]
