# Generated by Django 4.2.27 on 2025-12-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aasubsidy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctrineSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Doctrine System',
                'verbose_name_plural': 'Doctrine Systems',
            },
        ),
        migrations.AddField(
            model_name='doctrinesystem',
            name='is_active',
            field=models.BooleanField(default=True, help_text="If inactive, it won't be shown in the summary page or admin by default"),
        ),
        migrations.AddField(
            model_name='subsidyconfig',
            name='corporation_id',
            field=models.IntegerField(default=1, help_text='The ID of the corporation whose contracts should be subsidized'),
        ),
    ]
