# Generated by Django 4.2.23 on 2025-09-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0011_extend_industry_activites'),
        ('corptools', '0125_corporationaudit_last_change_industry_jobs_and_more'),
        ('fittings', '0017_doctrine_requested_fitting_requested_itemprices'),
        ('aasubsidy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access this app'), ('review_subsidy', 'Can Review/Approve/Deny Subsidies'), ('subsidy_admin', 'Can adjust subsidy settings'))},
        ),
        migrations.CreateModel(
            name='SubsidyItemPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('buy', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eve_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_price', to='eveuniverse.evetype')),
            ],
            options={
                'verbose_name': 'Subsidy Item Price',
                'verbose_name_plural': 'Subsidy Item Prices',
            },
        ),
        migrations.CreateModel(
            name='FittingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.IntegerField(default=0)),
                ('fitting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_request', to='fittings.fitting')),
            ],
            options={
                'verbose_name': 'Fitting Request',
                'verbose_name_plural': 'Fitting Requests',
            },
        ),
        migrations.CreateModel(
            name='CorporateContractSubsidy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.SmallIntegerField(default=0, help_text='1=Approved, -1=Rejected, 0=Pending')),
                ('subsidy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('paid', models.BooleanField(default=False)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aasubsidy_meta', to='corptools.corporatecontract')),
            ],
            options={
                'verbose_name': 'Corporate Contract Subsidy',
                'verbose_name_plural': 'Corporate Contract Subsidies',
            },
        ),
    ]
