# Generated by Django 4.2.27 on 2025-12-29 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aasubsidy', '0001_initial'),
        ('fittings', '0016_remove_dogmaattribute_type_remove_dogmaeffect_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctrineSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text="If inactive, it won't be shown in the summary page or admin by default")),
            ],
            options={
                'verbose_name': 'Doctrine System',
                'verbose_name_plural': 'Doctrine Systems',
            },
        ),
        migrations.CreateModel(
            name='FittingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.IntegerField(default=0)),
                ('fitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_requests', to='fittings.fitting')),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fitting_requests', to='aasubsidy.doctrinesystem')),
            ],
            options={
                'verbose_name': 'Fitting Request',
                'verbose_name_plural': 'Fitting Requests',
                'unique_together': {('system', 'fitting')},
            },
        ),
        migrations.AddField(
            model_name='subsidyconfig',
            name='corporation_id',
            field=models.IntegerField(default=1, help_text='The ID of the corporation whose contracts should be subsidized'),
        ),
    ]
