# Generated by Django 4.2.27 on 2025-12-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aasubsidy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrinesystem',
            name='is_active',
            field=models.BooleanField(default=True, help_text="If inactive, it won't be shown in the summary page or admin by default"),
        ),
        migrations.AddField(
            model_name='subsidyconfig',
            name='corporation_id',
            field=models.IntegerField(default=1, help_text='The ID of the corporation whose contracts should be subsidized'),
        ),
    ]
