# Generated by Django 4.2.23 on 2025-12-29 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0011_extend_industry_activites'),
        ('aasubsidy', '0002_doctrinesystem_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctrineLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(help_text='Station, Structure or System', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eveuniverse.eveentity')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='aasubsidy.doctrinesystem')),
            ],
            options={
                'verbose_name': 'Doctrine Location',
                'verbose_name_plural': 'Doctrine Locations',
                'unique_together': {('system', 'location')},
            },
        ),
    ]
