# Generated by Django 4.2.23 on 2025-09-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aasubsidy', '0002_alter_general_options_subsidyitemprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidyConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_basis', models.CharField(choices=[('sell', 'Jita Sell'), ('buy', 'Jita Buy')], default='sell', max_length=4)),
                ('pct_over_basis', models.DecimalField(decimal_places=4, default=0.1, help_text='e.g. 0.10 for 10%', max_digits=6)),
                ('cost_per_m3', models.DecimalField(decimal_places=4, default=250, max_digits=20)),
                ('rounding_increment', models.IntegerField(default=250000, help_text='ISK rounding increment')),
                ('deleted_check', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subsidy Configuration',
                'verbose_name_plural': 'Subsidy Configuration',
            },
        ),
    ]
