# Generated by Django 4.2.27 on 2026-04-28 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0011_extend_industry_activites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fittings", "0016_remove_dogmaattribute_type_remove_dogmaeffect_type_and_more"),
        ("corptools", "0127_alter_corporationaudit_options"),
        ("aasubsidy", "0003_doctrinelocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctrineMatchProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=True)),
                ("auto_match_threshold", models.DecimalField(decimal_places=2, default=95, max_digits=5)),
                ("review_threshold", models.DecimalField(decimal_places=2, default=80, max_digits=5)),
                ("allow_extra_items", models.BooleanField(default=True)),
                ("allow_meta_variants", models.BooleanField(default=False)),
                ("allow_faction_variants", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "fitting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_profile",
                        to="fittings.fitting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctrine Match Profile",
                "verbose_name_plural": "Doctrine Match Profiles",
            },
        ),
        migrations.CreateModel(
            name="DoctrineMatchResult",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "match_source",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("forced", "Forced"),
                            ("learned_rule", "Learned Rule"),
                            ("manual_accept", "Manual Accept"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched"),
                            ("needs_review", "Needs Review"),
                            ("rejected", "Rejected"),
                        ],
                        default="needs_review",
                        max_length=20,
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("hard_failures_json", models.TextField(blank=True, default="[]")),
                ("warnings_json", models.TextField(blank=True, default="[]")),
                ("evidence_json", models.TextField(blank=True, default="{}")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.OneToOneField(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctrine_match",
                        to="corptools.corporatecontract",
                    ),
                ),
                (
                    "matched_fitting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctrine_match_results",
                        to="fittings.fitting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctrine Match Result",
                "verbose_name_plural": "Doctrine Match Results",
                "indexes": [
                    models.Index(fields=["match_source"], name="dmr_match_source_idx"),
                    models.Index(fields=["match_status"], name="dmr_match_status_idx"),
                    models.Index(fields=["updated_at"], name="dmr_updated_at_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DoctrineContractDecision",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("accept_once", "Accept Once"),
                            ("reject_once", "Reject Once"),
                            ("create_rule", "Create Rule"),
                            ("create_variant", "Create Variant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("summary", models.CharField(default="", max_length=255)),
                ("details_json", models.TextField(blank=True, default="{}")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_decisions",
                        to="corptools.corporatecontract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fitting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="fittings.fitting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctrine Contract Decision",
                "verbose_name_plural": "Doctrine Contract Decisions",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["decision"], name="dcd_decision_idx"),
                    models.Index(fields=["created_at"], name="dcd_created_at_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DoctrineItemRule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rule_kind",
                    models.CharField(
                        choices=[
                            ("required", "Required"),
                            ("optional", "Optional"),
                            ("cargo", "Cargo"),
                            ("ignore", "Ignore"),
                        ],
                        default="required",
                        max_length=16,
                    ),
                ),
                (
                    "quantity_mode",
                    models.CharField(
                        choices=[("exact", "Exact"), ("minimum", "Minimum"), ("range", "Range")],
                        default="exact",
                        max_length=16,
                    ),
                ),
                ("expected_quantity", models.IntegerField(default=1)),
                ("min_quantity", models.IntegerField(default=0)),
                ("max_quantity", models.IntegerField(default=0)),
                ("category", models.CharField(default="module", max_length=32)),
                ("slot_label", models.CharField(blank=True, default="", max_length=64)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "eve_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="eveuniverse.evetype"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_rules",
                        to="aasubsidy.doctrinematchprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctrine Item Rule",
                "verbose_name_plural": "Doctrine Item Rules",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="DoctrineQuantityTolerance",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("absolute", "Absolute"),
                            ("percent", "Percent"),
                            ("missing_only", "Missing Only"),
                            ("extra_only", "Extra Only"),
                        ],
                        default="absolute",
                        max_length=16,
                    ),
                ),
                ("lower_bound", models.IntegerField(default=0)),
                ("upper_bound", models.IntegerField(default=0)),
                ("penalty_points", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    "eve_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="eveuniverse.evetype"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quantity_tolerances",
                        to="aasubsidy.doctrinematchprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctrine Quantity Tolerance",
                "verbose_name_plural": "Doctrine Quantity Tolerances",
                "ordering": ("eve_type_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="DoctrineSubstitutionRule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("specific", "Specific Type Substitute"),
                            ("meta_family", "Same Meta Family"),
                            ("market_group", "Same Market Group"),
                            ("group", "Same Group"),
                        ],
                        default="specific",
                        max_length=20,
                    ),
                ),
                ("max_meta_level_delta", models.IntegerField(default=0)),
                ("same_slot_only", models.BooleanField(default=True)),
                ("same_group_only", models.BooleanField(default=True)),
                ("penalty_points", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "allowed_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "expected_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="eveuniverse.evetype"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutions",
                        to="aasubsidy.doctrinematchprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctrine Substitution Rule",
                "verbose_name_plural": "Doctrine Substitution Rules",
                "ordering": ("expected_type_id", "id"),
            },
        ),
    ]
