# Generated by Django 4.2.23 on 2025-09-24 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aasubsidy', '0003_subsidyconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTablePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_key', models.CharField(db_index=True, default='contracts', max_length=100)),
                ('sort_idx', models.IntegerField(default=0)),
                ('sort_dir', models.CharField(default='desc', max_length=4)),
                ('filters_json', models.TextField(blank=True, default='{}')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aasubsidy_table_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Table Preference',
                'verbose_name_plural': 'User Table Preferences',
                'unique_together': {('user', 'table_key')},
            },
        ),
    ]
