# Generated by Django 4.2.27 on 2026-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aasubsidy", "0004_doctrine_matching_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsidyconfig",
            name="ignore_zero_isk_contracts",
            field=models.BooleanField(default=True, help_text="Ignore zero-ISK contracts in subsidy workflows"),
        ),
        migrations.AddField(
            model_name="subsidyconfig",
            name="ignored_contract_title_patterns",
            field=models.TextField(
                blank=True,
                default="INDY-*",
                help_text="One wildcard pattern per line. Use * to match any sequence.",
            ),
        ),
    ]
