# Generated by Django 4.2.23 on 2025-09-24 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fittings', '0017_doctrine_requested_fitting_requested_itemprices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aasubsidy', '0004_usertablepreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='FittingClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_claims', to='fittings.fitting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_fitting_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fitting Claim',
                'verbose_name_plural': 'Fitting Claims',
                'unique_together': {('fitting', 'user')},
            },
        ),
    ]
