# Generated by Django 4.2.23 on 2025-09-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aasubsidy', '0005_fittingclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatecontractsubsidy',
            name='exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='corporatecontractsubsidy',
            constraint=models.UniqueConstraint(fields=('contract',), name='uniq_subsidy_per_contract'),
        ),
    ]
