# Generated by Django 4.2.27 on 2026-04-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aasubsidy", "0005_subsidyconfig_contract_exclusions"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsidyconfig",
            name="close_match_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=70.00,
                help_text="Minimum score (0-100) for a contract to be considered a 'close match' and require review. Below this score, contracts will be rejected automatically.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="subsidyconfig",
            name="show_close_matches",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, close matches (below auto-accept but above threshold) will appear on the review board. If disabled, only perfect matches and forced doctrines will be shown.",
            ),
        ),
    ]
