# Generated by Django 4.2.23 on 2025-10-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fittings', '0018_itempricesfittings_delete_itemprices'),
        ('aasubsidy', '0006_corporatecontractsubsidy_exempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatecontractsubsidy',
            name='forced_fitting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forced_contracts', to='fittings.fitting'),
        ),
    ]
