# Generated by Django 4.2.27 on 2026-04-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aasubsidy", "0006_subsidyconfig_matching_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("corptools", "0127_alter_corporationaudit_options"),
        ("fittings", "0016_remove_dogmaattribute_type_remove_dogmaeffect_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FittingClaimAutoClearance",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.OneToOneField(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aasubsidy_claim_clearance",
                        to="corptools.corporatecontract",
                    ),
                ),
                (
                    "fitting",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="fittings.fitting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fitting Claim Auto Clearance",
                "verbose_name_plural": "Fitting Claim Auto Clearances",
                "indexes": [
                    models.Index(fields=["user", "fitting"], name="fca_user_fitting_idx"),
                    models.Index(fields=["created_at"], name="fca_created_at_idx"),
                ],
            },
        ),
    ]
